# Generated by Django 5.0.6 on 2024-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveIntegerField(verbose_name='возраст'),
        ),
    ]
