# Generated by Django 5.0.6 on 2024-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255, verbose_name='название болезни')),
                ('prescription', models.TextField(verbose_name='назначение')),
            ],
            options={
                'verbose_name': 'История болезни',
                'verbose_name_plural': 'Истории болезней',
            },
        ),
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='patient_photo/', verbose_name='фото')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10, verbose_name='пол')),
                ('nationality', models.CharField(max_length=150, verbose_name='гражданство')),
                ('document_number', models.CharField(max_length=150, verbose_name='№ документа')),
                ('document_expiry_date', models.DateField(verbose_name='срок действия')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Место рождения')),
                ('authority', models.CharField(max_length=150, verbose_name='Орган выдачи')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('personal_number', models.CharField(max_length=150, unique=True, verbose_name='Персональный номер')),
            ],
            options={
                'verbose_name': 'Карта пациента',
                'verbose_name_plural': 'Карты пациентов',
            },
        ),
    ]
