# Generated by Django 5.0.6 on 2024-07-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasehistory',
            name='Nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dis_his', to='users.nurse'),
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dis_history', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='patient_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_history', to='patients.patientcard'),
        ),
    ]
